[book]
authors = ["James Eapen"]
language = "en"
multilingual = false
src = "src"
title = "wiki"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/jamespeapen/wiki"

[output.html.fold]
enable = true
level = 0
